name: Create Release and Zip

on:
  push:
    tags:
      - '*'   # Trigger on new tags
  workflow_dispatch:  # Allow manual trigger with tag input
    inputs:
      tag:
        description: 'Tag to release'
        required: true

jobs:
  create_release:
    name: Create and upload release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up the tag variable
      id: tag_name
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Install zip utility
      run: sudo apt-get install zip

    - name: Create zip excluding .xcf files
      run: |
        zip "barrel_stages_${{ steps.tag_name.outputs.TAG }}.zip" -x '*.xcf' 'barrel_stages/*'

    - name: Create GitHub release
      uses: actions/create-release@1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_name.outputs.TAG }}
        release_name: Release ${{ steps.tag_name.outputs.TAG }}
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./barrel_stages_${{ steps.tag_name.outputs.TAG }}.zip
        asset_name: barrel_stages_${{ steps.tag_name.outputs.TAG }}.zip
        asset_content_type: application/zip
